# Thing configuration
Thing:
  #Id: <thing_id>
  Model: <thing_model>
  Name: <thing_name>
  User: <thing_user>
  PortPublic: <thing_port_public>
  PortPrivate: <thing_port_private>

# Mother configuration
Mother:
  Host: <mother_host>
  User: <mother_user>
  Key: <mother_key>
