# Thing configuration
Thing:
  #Id: <thing_id>
  Model: <thing_model>
  Name: <thing_name>
  User: <thing_user>
  PortPublic: <thing_port_public>
  PortPrivate: <thing_port_private>

# Hub configuration
Hub:
  Host: <hub_host>
  User: <hub_user>
  Key: <hub_key>
