#!/bin/bash

git diff --exit-code >/dev/null
if [ $? -ne 0 ]; then
    echo "local, unstaged changes; aborting"
    exit 1
fi

git diff --cached --exit-code >/dev/null
if [ $? -ne 0 ]; then
    echo "staged changes but not commited; aborting"
    exit 1
fi

git status | grep "Your branch is up to date" >/dev/null
if [ $? -ne 0 ]; then
    echo "commits not pushed; aborting"
    exit 1
fi

git tag | tail -n5

read -p "New Version: " ver

git tag ${ver}
git push origin ${ver}
GOPROXY=proxy.golang.org go list -m github.com/scottfeldman/merle@${ver}
